version: "3"

services:
  db:
    image: postgres
    restart: always
    env_file:
     - .env 
    volumes:
      - ./db/data:/var/lib/postgresql/data
  backend:
    build:
      context: .
    env_file:
     - .env
    ports:
      - "3030:3030"
      - "9230:9229"
    volumes:
      - ./config:/app/config
      - ./src:/app/src
    depends_on:
      - db
    command: sh -c "/wait && npm run dev"
